// Dữ liệu từ vựng theo giáo trình Minna no Nihongo (N5 và N4)
// Cấu trúc: COURSE_DATA[Level][Bài học] = [{ jp, kana, rom, mean }, ...]

const COURSE_DATA = {
  "N5": {
    "Bài 1": [
      { jp: "私", kana: "わたし", rom: "watashi", mean: "tôi" },
      { jp: "私たち", kana: "わたしたち", rom: "watashitachi", mean: "chúng ta, chúng tôi" },
      { jp: "あなた", kana: "あなた", rom: "anata", mean: "bạn, anh, chị" },
      { jp: "あの人", kana: "あのひと", rom: "ano hito", mean: "người kia, người đó" },
      { jp: "皆さん", kana: "みなさん", rom: "minasan", mean: "mọi người" },
      { jp: "先生", kana: "せんせい", rom: "sensei", mean: "thầy, cô (không dùng gọi mình)" },
      { jp: "教師", kana: "きょうし", rom: "kyoushi", mean: "giáo viên (nghề nghiệp)" },
      { jp: "学生", kana: "がくせい", rom: "gakusei", mean: "học sinh, sinh viên" },
      { jp: "会社員", kana: "かいしゃいん", rom: "kaishain", mean: "nhân viên công ty" },
      { jp: "社員", kana: "しゃいん", rom: "shain", mean: "nhân viên công ty ~" },
      { jp: "銀行員", kana: "ぎんこういん", rom: "ginkouin", mean: "nhân viên ngân hàng" },
      { jp: "医者", kana: "いしゃ", rom: "isha", mean: "bác sĩ" },
      { jp: "研究者", kana: "けんきゅうしゃ", rom: "kenkyuusha", mean: "nhà nghiên cứu" },
      { jp: "大学", kana: "だいがく", rom: "daigaku", mean: "đại học" },
      { jp: "病院", kana: "びょういん", rom: "byouin", mean: "bệnh viện" },
      { jp: "だれ", kana: "だれ", rom: "dare", mean: "ai" },
      { jp: "～歳", kana: "～さい", rom: "-sai", mean: "tuổi" },
      { jp: "何歳", kana: "なんさい", rom: "nansai", mean: "mấy tuổi" }
    ],
    "Bài 2": [
      { jp: "これ", kana: "これ", rom: "kore", mean: "cái này" },
      { jp: "それ", kana: "それ", rom: "sore", mean: "cái đó" },
      { jp: "あれ", kana: "あれ", rom: "are", mean: "cái kia" },
      { jp: "この", kana: "この", rom: "kono", mean: "~ này" },
      { jp: "その", kana: "その", rom: "sono", mean: "~ đó" },
      { jp: "あの", kana: "あの", rom: "ano", mean: "~ kia" },
      { jp: "本", kana: "ほん", rom: "hon", mean: "sách" },
      { jp: "辞書", kana: "じしょ", rom: "jisho", mean: "từ điển" },
      { jp: "雑誌", kana: "ざっし", rom: "zasshi", mean: "tạp chí" },
      { jp: "新聞", kana: "しんぶん", rom: "shinbun", mean: "báo" },
      { jp: "ノート", kana: "のーと", rom: "nooto", mean: "vở" },
      { jp: "手帳", kana: "てちょう", rom: "techou", mean: "sổ tay" },
      { jp: "名刺", kana: "めいし", rom: "meishi", mean: "danh thiếp" },
      { jp: "カード", kana: "かーど", rom: "kaado", mean: "thẻ" },
      { jp: "鉛筆", kana: "えんぴつ", rom: "enpitsu", mean: "bút chì" },
      { jp: "時計", kana: "とけい", rom: "tokei", mean: "đồng hồ" },
      { jp: "傘", kana: "かさ", rom: "kasa", mean: "ô, dù" },
      { jp: "かばん", kana: "かばん", rom: "kaban", mean: "cặp, túi xách" }
    ],
    "Bài 3": [
      { jp: "ここ", kana: "ここ", rom: "koko", mean: "chỗ này" },
      { jp: "そこ", kana: "そこ", rom: "soko", mean: "chỗ đó" },
      { jp: "あそこ", kana: "あそこ", rom: "asoko", mean: "chỗ kia" },
      { jp: "どこ", kana: "どこ", rom: "doko", mean: "chỗ nào, đâu" },
      { jp: "こちら", kana: "こちら", rom: "kochira", mean: "phía này (lịch sự của koko)" },
      { jp: "そちら", kana: "そちら", rom: "sochira", mean: "phía đó (lịch sự của soko)" },
      { jp: "あちら", kana: "あちら", rom: "achira", mean: "phía kia (lịch sự của asoko)" },
      { jp: "どちら", kana: "どちら", rom: "dochira", mean: "phía nào (lịch sự của doko)" },
      { jp: "教室", kana: "きょうしつ", rom: "kyoushitsu", mean: "phòng học" },
      { jp: "食堂", kana: "しょくどう", rom: "shokudou", mean: "nhà ăn" },
      { jp: "事務所", kana: "じむしょ", rom: "jimusho", mean: "văn phòng" },
      { jp: "会議室", kana: "かいぎしつ", rom: "kaigishitsu", mean: "phòng họp" },
      { jp: "受付", kana: "うけつけ", rom: "uketsuke", mean: "bộ phận tiếp tân" },
      { jp: "部屋", kana: "へや", rom: "heya", mean: "căn phòng" },
      { jp: "トイレ", kana: "といれ", rom: "toire", mean: "nhà vệ sinh" },
      { jp: "階段", kana: "かいだん", rom: "kaidan", mean: "cầu thang" },
      { jp: "国", kana: "くに", rom: "kuni", mean: "đất nước" },
      { jp: "会社", kana: "かいしゃ", rom: "kaisha", mean: "công ty" },
      { jp: "家", kana: "うち", rom: "uchi", mean: "nhà" }
    ],
    "Bài 4": [
      { jp: "起きます", kana: "おきます", rom: "okimasu", mean: "dậy, thức dậy" },
      { jp: "寝ます", kana: "ねます", rom: "nemasu", mean: "ngủ, đi ngủ" },
      { jp: "働きます", kana: "はたらきます", rom: "hatarakimasu", mean: "làm việc" },
      { jp: "休みます", kana: "やすみます", rom: "yasumimasu", mean: "nghỉ ngơi" },
      { jp: "勉強します", kana: "べんきょうします", rom: "benkyoushimasu", mean: "học tập" },
      { jp: "終わります", kana: "おわります", rom: "owarimasu", mean: "kết thúc, xong" },
      { jp: "デパート", kana: "でぱーと", rom: "depaato", mean: "bách hóa" },
      { jp: "銀行", kana: "ぎんこう", rom: "ginkou", mean: "ngân hàng" },
      { jp: "郵便局", kana: "ゆうびんきょく", rom: "yuubinkyoku", mean: "bưu điện" },
      { jp: "図書館", kana: "としょかん", rom: "toshokan", mean: "thư viện" },
      { jp: "美術館", kana: "びじゅつかん", rom: "bijutsukan", mean: "bảo tàng mỹ thuật" },
      { jp: "今", kana: "いま", rom: "ima", mean: "bây giờ" },
      { jp: "～時", kana: "～じ", rom: "-ji", mean: "giờ" },
      { jp: "～分", kana: "～ふん", rom: "-fun", mean: "phút" },
      { jp: "半", kana: "はん", rom: "han", mean: "rưỡi, nửa" }
    ],
    "Bài 5": [
      { jp: "行きます", kana: "いきます", rom: "ikimasu", mean: "đi" },
      { jp: "来ます", kana: "きます", rom: "kimasu", mean: "đến" },
      { jp: "帰ります", kana: "かえります", rom: "kaerimasu", mean: "về" },
      { jp: "学校", kana: "がっこう", rom: "gakkou", mean: "trường học" },
      { jp: "スーパー", kana: "すーぱー", rom: "suupaa", mean: "siêu thị" },
      { jp: "駅", kana: "えき", rom: "eki", mean: "nhà ga" },
      { jp: "飛行機", kana: "ひこうき", rom: "hikouki", mean: "máy bay" },
      { jp: "船", kana: "ふね", rom: "fune", mean: "thuyền, tàu thủy" },
      { jp: "電車", kana: "でんしゃ", rom: "densha", mean: "tàu điện" },
      { jp: "地下鉄", kana: "ちかてつ", rom: "chikatetsu", mean: "tàu điện ngầm" },
      { jp: "新幹線", kana: "しんかんせん", rom: "shinkansen", mean: "shinkansen (tàu siêu tốc)" },
      { jp: "バス", kana: "ばす", rom: "basu", mean: "xe buýt" },
      { jp: "タクシー", kana: "たくしー", rom: "takushii", mean: "taxi" },
      { jp: "自転車", kana: "じてんしゃ", rom: "jitensha", mean: "xe đạp" },
      { jp: "歩いて", kana: "あるいて", rom: "aruite", mean: "đi bộ" },
      { jp: "人", kana: "ひと", rom: "hito", mean: "người" },
      { jp: "友達", kana: "ともだち", rom: "tomodachi", mean: "bạn bè" },
      { jp: "彼", kana: "かれ", rom: "kare", mean: "anh ấy" },
      { jp: "彼女", kana: "かのじょ", rom: "kanojo", mean: "cô ấy" },
      { jp: "家族", kana: "かぞく", rom: "kazoku", mean: "gia đình" }
    ],
    "Bài 6": [
      { jp: "食べます", kana: "たべます", rom: "tabemasu", mean: "ăn" },
      { jp: "飲みます", kana: "のみます", rom: "nomimasu", mean: "uống" },
      { jp: "吸います", kana: "すいます", rom: "suimasu", mean: "hút (thuốc)" },
      { jp: "見ます", kana: "みます", rom: "mimasu", mean: "xem, nhìn" },
      { jp: "聞きます", kana: "ききます", rom: "kikimasu", mean: "nghe" },
      { jp: "読みます", kana: "よみます", rom: "yomimasu", mean: "đọc" },
      { jp: "書きます", kana: "かきます", rom: "kakimasu", mean: "viết" },
      { jp: "買います", kana: "かいます", rom: "kaimasu", mean: "mua" },
      { jp: "撮ります", kana: "とります", rom: "torimasu", mean: "chụp (ảnh)" },
      { jp: "します", kana: "します", rom: "shimasu", mean: "làm" },
      { jp: "会います", kana: "あいます", rom: "aimasu", mean: "gặp" },
      { jp: "ごはん", kana: "ごはん", rom: "gohan", mean: "cơm, bữa ăn" },
      { jp: "朝ごはん", kana: "あさごはん", rom: "asagohan", mean: "bữa sáng" },
      { jp: "昼ごはん", kana: "ひるごはん", rom: "hirugohan", mean: "bữa trưa" },
      { jp: "晩ごはん", kana: "ばんごはん", rom: "bangohan", mean: "bữa tối" },
      { jp: "パン", kana: "ぱん", rom: "pan", mean: "bánh mì" },
      { jp: "卵", kana: "たまご", rom: "tamago", mean: "trứng" },
      { jp: "肉", kana: "にく", rom: "niku", mean: "thịt" },
      { jp: "魚", kana: "さかな", rom: "sakana", mean: "cá" },
      { jp: "野菜", kana: "やさい", rom: "yasai", mean: "rau" },
      { jp: "果物", kana: "くだもの", rom: "kudamono", mean: "hoa quả" },
      { jp: "水", kana: "みず", rom: "mizu", mean: "nước" },
      { jp: "お茶", kana: "おちゃ", rom: "ocha", mean: "trà" },
      { jp: "コーヒー", kana: "こーひー", rom: "koohii", mean: "cà phê" },
      { jp: "牛乳", kana: "ぎゅうにゅう", rom: "gyuunyuu", mean: "sữa bò" },
      { jp: "ジュース", kana: "じゅーす", rom: "juusu", mean: "nước ép" },
      { jp: "ビール", kana: "びーる", rom: "biiru", mean: "bia" },
      { jp: "お酒", kana: "おさけ", rom: "osake", mean: "rượu" }
    ],
    "Bài 7": [
      { jp: "切ります", kana: "きります", rom: "kirimasu", mean: "cắt" },
      { jp: "送ります", kana: "おくります", rom: "okurimasu", mean: "gửi" },
      { jp: "あげます", kana: "あげます", rom: "agemasu", mean: "cho, tặng" },
      { jp: "もらいます", kana: "もらいます", rom: "moraimasu", mean: "nhận" },
      { jp: "貸します", kana: "かします", rom: "kashimasu", mean: "cho mượn" },
      { jp: "借ります", kana: "かります", rom: "karimasu", mean: "mượn" },
      { jp: "教えます", kana: "おしえます", rom: "oshiemasu", mean: "dạy, chỉ" },
      { jp: "習います", kana: "ならいます", rom: "naraimasu", mean: "học (từ ai)" },
      { jp: "かけます", kana: "かけます", rom: "kakemasu", mean: "gọi (điện thoại)" },
      { jp: "手", kana: "て", rom: "te", mean: "tay" },
      { jp: "はし", kana: "はし", rom: "hashi", mean: "đũa" },
      { jp: "スプーン", kana: "すぷーん", rom: "supuun", mean: "thìa" },
      { jp: "ナイフ", kana: "ないふ", rom: "naifu", mean: "dao" },
      { jp: "フォーク", kana: "ふぉーく", rom: "fooku", mean: "dĩa" },
      { jp: "花", kana: "はな", rom: "hana", mean: "hoa" },
      { jp: "チョコレート", kana: "ちょこれーと", rom: "chokoreeto", mean: "sô-cô-la" },
      { jp: "プレゼント", kana: "ぷれぜんと", rom: "purezento", mean: "quà tặng" }
    ],
    "Bài 8": [
      { jp: "ハンサム", kana: "はんさむ", rom: "hansamu", mean: "đẹp trai" },
      { jp: "きれい", kana: "きれい", rom: "kirei", mean: "đẹp, sạch" },
      { jp: "静か", kana: "しずか", rom: "shizuka", mean: "yên tĩnh" },
      { jp: "にぎやか", kana: "にぎやか", rom: "nigiyaka", mean: "nhộn nhịp" },
      { jp: "有名", kana: "ゆうめい", rom: "yuumei", mean: "nổi tiếng" },
      { jp: "親切", kana: "しんせつ", rom: "shinsetsu", mean: "tốt bụng" },
      { jp: "元気", kana: "げんき", rom: "genki", mean: "khỏe mạnh" },
      { jp: "暇", kana: "ひま", rom: "hima", mean: "rảnh rỗi" },
      { jp: "便利", kana: "べんり", rom: "benri", mean: "tiện lợi" },
      { jp: "大きい", kana: "おおきい", rom: "ookii", mean: "to, lớn" },
      { jp: "小さい", kana: "ちいさい", rom: "chiisai", mean: "nhỏ, bé" },
      { jp: "新しい", kana: "あたらしい", rom: "atarashii", mean: "mới" },
      { jp: "古い", kana: "ふるい", rom: "furui", mean: "cũ" },
      { jp: "いい", kana: "いい", rom: "ii", mean: "tốt, hay" },
      { jp: "悪い", kana: "わるい", rom: "warui", mean: "xấu, tệ" },
      { jp: "暑い", kana: "あつい", rom: "atsui", mean: "nóng (thời tiết)" },
      { jp: "寒い", kana: "さむい", rom: "samui", mean: "lạnh (thời tiết)" },
      { jp: "熱い", kana: "あつい", rom: "atsui", mean: "nóng (đồ vật)" },
      { jp: "冷たい", kana: "つめたい", rom: "tsumetai", mean: "lạnh (đồ vật)" },
      { jp: "難しい", kana: "むずかしい", rom: "muzukashii", mean: "khó" },
      { jp: "やさしい", kana: "やさしい", rom: "yasashii", mean: "dễ, hiền" },
      { jp: "高い", kana: "たかい", rom: "takai", mean: "cao, đắt" },
      { jp: "安い", kana: "やすい", rom: "yasui", mean: "rẻ" },
      { jp: "低い", kana: "ひくい", rom: "hikui", mean: "thấp" },
      { jp: "おもしろい", kana: "おもしろい", rom: "omoshiroi", mean: "thú vị" },
      { jp: "おいしい", kana: "おいしい", rom: "oishii", mean: "ngon" },
      { jp: "忙しい", kana: "いそがしい", rom: "isogashii", mean: "bận" },
      { jp: "楽しい", kana: "たのしい", rom: "tanoshii", mean: "vui" },
      { jp: "白い", kana: "しろい", rom: "shiroi", mean: "trắng" },
      { jp: "黒い", kana: "くろい", rom: "kuroi", mean: "đen" },
      { jp: "赤い", kana: "あかい", rom: "akai", mean: "đỏ" },
      { jp: "青い", kana: "あおい", rom: "aoi", mean: "xanh" }
    ],
    "Bài 9": [
      { jp: "わかります", kana: "わかります", rom: "wakarimasu", mean: "hiểu" },
      { jp: "あります", kana: "あります", rom: "arimasu", mean: "có (đồ vật)" },
      { jp: "好き", kana: "すき", rom: "suki", mean: "thích" },
      { jp: "嫌い", kana: "きらい", rom: "kirai", mean: "ghét" },
      { jp: "上手", kana: "じょうず", rom: "jouzu", mean: "giỏi, khéo" },
      { jp: "下手", kana: "へた", rom: "heta", mean: "kém, dở" },
      { jp: "料理", kana: "りょうり", rom: "ryouri", mean: "nấu ăn, món ăn" },
      { jp: "飲み物", kana: "のみもの", rom: "nomimono", mean: "đồ uống" },
      { jp: "スポーツ", kana: "すぽーつ", rom: "supootsu", mean: "thể thao" },
      { jp: "野球", kana: "やきゅう", rom: "yakyuu", mean: "bóng chày" },
      { jp: "ダンス", kana: "だんす", rom: "dansu", mean: "nhảy, khiêu vũ" },
      { jp: "音楽", kana: "おんがく", rom: "ongaku", mean: "âm nhạc" },
      { jp: "歌", kana: "うた", rom: "uta", mean: "bài hát" },
      { jp: "映画", kana: "えいが", rom: "eiga", mean: "phim" },
      { jp: "よく", kana: "よく", rom: "yoku", mean: "thường xuyên, giỏi" },
      { jp: "だいたい", kana: "だいたい", rom: "daitai", mean: "đại khái" },
      { jp: "たくさん", kana: "たくさん", rom: "takusan", mean: "nhiều" },
      { jp: "少し", kana: "すこし", rom: "sukoshi", mean: "một ít" },
      { jp: "全然", kana: "ぜんぜん", rom: "zenzen", mean: "hoàn toàn (không)" },
      { jp: "どうして", kana: "どうして", rom: "doushite", mean: "tại sao" }
    ],
    "Bài 10": [
      { jp: "います", kana: "います", rom: "imasu", mean: "có, ở (sinh vật)" },
      { jp: "あります", kana: "あります", rom: "arimasu", mean: "có, ở (đồ vật)" },
      { jp: "上", kana: "うえ", rom: "ue", mean: "trên" },
      { jp: "下", kana: "した", rom: "shita", mean: "dưới" },
      { jp: "前", kana: "まえ", rom: "mae", mean: "trước" },
      { jp: "後ろ", kana: "うしろ", rom: "ushiro", mean: "sau" },
      { jp: "右", kana: "みぎ", rom: "migi", mean: "phải" },
      { jp: "左", kana: "ひだり", rom: "hidari", mean: "trái" },
      { jp: "中", kana: "なか", rom: "naka", mean: "trong, bên trong" },
      { jp: "外", kana: "そと", rom: "soto", mean: "ngoài, bên ngoài" },
      { jp: "隣", kana: "となり", rom: "tonari", mean: "bên cạnh" },
      { jp: "近く", kana: "ちかく", rom: "chikaku", mean: "gần" },
      { jp: "間", kana: "あいだ", rom: "aida", mean: "giữa" },
      { jp: "男の人", kana: "おとこのひと", rom: "otoko no hito", mean: "đàn ông" },
      { jp: "女の人", kana: "おんなのひと", rom: "onna no hito", mean: "phụ nữ" },
      { jp: "男の子", kana: "おとこのこ", rom: "otoko no ko", mean: "con trai" },
      { jp: "女の子", kana: "おんなのこ", rom: "onna no ko", mean: "con gái" },
      { jp: "犬", kana: "いぬ", rom: "inu", mean: "chó" },
      { jp: "猫", kana: "ねこ", rom: "neko", mean: "mèo" },
      { jp: "木", kana: "き", rom: "ki", mean: "cây" },
      { jp: "公園", kana: "こうえん", rom: "kouen", mean: "công viên" },
      { jp: "店", kana: "みせ", rom: "mise", mean: "cửa hàng" },
      { jp: "レストラン", kana: "れすとらん", rom: "resutoran", mean: "nhà hàng" },
      { jp: "電気", kana: "でんき", rom: "denki", mean: "đèn, điện" },
      { jp: "テーブル", kana: "てーぶる", rom: "teeburu", mean: "bàn" },
      { jp: "ベッド", kana: "べっど", rom: "beddo", mean: "giường" },
      { jp: "棚", kana: "たな", rom: "tana", mean: "giá, kệ" },
      { jp: "箱", kana: "はこ", rom: "hako", mean: "hộp" }
    ],
    "Bài 11": [
      { jp: "一つ", kana: "ひとつ", rom: "hitotsu", mean: "1 cái" },
      { jp: "二つ", kana: "ふたつ", rom: "futatsu", mean: "2 cái" },
      { jp: "三つ", kana: "みっつ", rom: "mittsu", mean: "3 cái" },
      { jp: "四つ", kana: "よっつ", rom: "yottsu", mean: "4 cái" },
      { jp: "五つ", kana: "いつつ", rom: "itsutsu", mean: "5 cái" },
      { jp: "六つ", kana: "むっつ", rom: "muttsu", mean: "6 cái" },
      { jp: "七つ", kana: "ななつ", rom: "nanatsu", mean: "7 cái" },
      { jp: "八つ", kana: "やっつ", rom: "yattsu", mean: "8 cái" },
      { jp: "九つ", kana: "ここのつ", rom: "kokonotsu", mean: "9 cái" },
      { jp: "十", kana: "とお", rom: "too", mean: "10 cái" },
      { jp: "いくつ", kana: "いくつ", rom: "ikutsu", mean: "mấy cái, bao nhiêu" },
      { jp: "一人", kana: "ひとり", rom: "hitori", mean: "1 người" },
      { jp: "二人", kana: "ふたり", rom: "futari", mean: "2 người" },
      { jp: "～台", kana: "～だい", rom: "-dai", mean: "~ chiếc (máy, xe)" },
      { jp: "～枚", kana: "～まい", rom: "-mai", mean: "~ tờ, tấm" },
      { jp: "～回", kana: "～かい", rom: "-kai", mean: "~ lần" },
      { jp: "りんご", kana: "りんご", rom: "ringo", mean: "táo" },
      { jp: "みかん", kana: "みかん", rom: "mikan", mean: "quýt" },
      { jp: "切手", kana: "きって", rom: "kitte", mean: "tem" },
      { jp: "封筒", kana: "ふうとう", rom: "fuutou", mean: "phong bì" },
      { jp: "外国人", kana: "がいこくじん", rom: "gaikokujin", mean: "người nước ngoài" }
    ],
    "Bài 12": [
      { jp: "簡単", kana: "かんたん", rom: "kantan", mean: "đơn giản" },
      { jp: "近い", kana: "ちかい", rom: "chikai", mean: "gần" },
      { jp: "遠い", kana: "とおい", rom: "tooi", mean: "xa" },
      { jp: "速い", kana: "はやい", rom: "hayai", mean: "nhanh" },
      { jp: "遅い", kana: "おそい", rom: "osoi", mean: "chậm, muộn" },
      { jp: "多い", kana: "おおい", rom: "ooi", mean: "nhiều" },
      { jp: "少ない", kana: "すくない", rom: "sukunai", mean: "ít" },
      { jp: "暖かい", kana: "あたたかい", rom: "atatakai", mean: "ấm áp" },
      { jp: "涼しい", kana: "すずしい", rom: "suzushii", mean: "mát mẻ" },
      { jp: "甘い", kana: "あまい", rom: "amai", mean: "ngọt" },
      { jp: "辛い", kana: "からい", rom: "karai", mean: "cay" },
      { jp: "重い", kana: "おもい", rom: "omoi", mean: "nặng" },
      { jp: "軽い", kana: "かるい", rom: "karui", mean: "nhẹ" },
      { jp: "季節", kana: "きせつ", rom: "kisetsu", mean: "mùa" },
      { jp: "春", kana: "はる", rom: "haru", mean: "mùa xuân" },
      { jp: "夏", kana: "なつ", rom: "natsu", mean: "mùa hè" },
      { jp: "秋", kana: "あき", rom: "aki", mean: "mùa thu" },
      { jp: "冬", kana: "ふゆ", rom: "fuyu", mean: "mùa đông" },
      { jp: "天気", kana: "てんき", rom: "tenki", mean: "thời tiết" },
      { jp: "雨", kana: "あめ", rom: "ame", mean: "mưa" },
      { jp: "雪", kana: "ゆき", rom: "yuki", mean: "tuyết" },
      { jp: "曇り", kana: "くもり", rom: "kumori", mean: "trời nhiều mây" },
      { jp: "町", kana: "まち", rom: "machi", mean: "thị trấn, phố" },
      { jp: "食べ物", kana: "たべもの", rom: "tabemono", mean: "đồ ăn" }
    ],
    "Bài 13": [
      { jp: "遊びます", kana: "あそびます", rom: "asobimasu", mean: "chơi" },
      { jp: "泳ぎます", kana: "およぎます", rom: "oyogimasu", mean: "bơi" },
      { jp: "迎えに行きます", kana: "むかえにいきます", rom: "mukae ni ikimasu", mean: "đi đón" },
      { jp: "疲れます", kana: "つかれます", rom: "tsukaremasu", mean: "mệt" },
      { jp: "出します", kana: "だします", rom: "dashimasu", mean: "gửi (thư), nộp" },
      { jp: "入ります", kana: "はいります", rom: "hairimasu", mean: "vào" },
      { jp: "出ます", kana: "でます", rom: "demasu", mean: "ra" },
      { jp: "結婚します", kana: "けっこんします", rom: "kekkonshimasu", mean: "kết hôn" },
      { jp: "買い物します", kana: "かいものします", rom: "kaimonoshimasu", mean: "mua sắm" },
      { jp: "食事します", kana: "しょくじします", rom: "shokujishimasu", mean: "dùng bữa" },
      { jp: "散歩します", kana: "さんぽします", rom: "sanposhimasu", mean: "đi dạo" },
      { jp: "欲しい", kana: "ほしい", rom: "hoshii", mean: "muốn (đồ vật)" },
      { jp: "広い", kana: "ひろい", rom: "hiroi", mean: "rộng" },
      { jp: "狭い", kana: "せまい", rom: "semai", mean: "hẹp" },
      { jp: "お腹がすきます", kana: "おなかがすきます", rom: "onaka ga sukimasu", mean: "đói bụng" },
      { jp: "喉が渇きます", kana: "のどがかわきます", rom: "nodo ga kawakimasu", mean: "khát nước" },
      { jp: "子供", kana: "こども", rom: "kodomo", mean: "trẻ con" },
      { jp: "プール", kana: "ぷーる", rom: "puuru", mean: "bể bơi" },
      { jp: "海", kana: "うみ", rom: "umi", mean: "biển" },
      { jp: "川", kana: "かわ", rom: "kawa", mean: "sông" },
      { jp: "山", kana: "やま", rom: "yama", mean: "núi" },
      { jp: "お寺", kana: "おてら", rom: "otera", mean: "chùa" },
      { jp: "神社", kana: "じんじゃ", rom: "jinja", mean: "đền thần" }
    ],
    "Bài 14": [
      { jp: "つけます", kana: "つけます", rom: "tsukemasu", mean: "bật (đèn, máy)" },
      { jp: "消します", kana: "けします", rom: "keshimasu", mean: "tắt (đèn, máy)" },
      { jp: "開けます", kana: "あけます", rom: "akemasu", mean: "mở" },
      { jp: "閉めます", kana: "しめます", rom: "shimemasu", mean: "đóng" },
      { jp: "急ぎます", kana: "いそぎます", rom: "isogimasu", mean: "vội, gấp" },
      { jp: "待ちます", kana: "まちます", rom: "machimasu", mean: "chờ, đợi" },
      { jp: "止めます", kana: "とめます", rom: "tomemasu", mean: "dừng lại" },
      { jp: "曲がります", kana: "まがります", rom: "magarimasu", mean: "rẽ, quẹo" },
      { jp: "持ちます", kana: "もちます", rom: "mochimasu", mean: "cầm, mang" },
      { jp: "取ります", kana: "とります", rom: "torimasu", mean: "lấy" },
      { jp: "手伝います", kana: "てつだいます", rom: "tetsudaimasu", mean: "giúp đỡ" },
      { jp: "呼びます", kana: "よびます", rom: "yobimasu", mean: "gọi" },
      { jp: "話します", kana: "はなします", rom: "hanashimasu", mean: "nói chuyện" },
      { jp: "使います", kana: "つかいます", rom: "tsukaimasu", mean: "sử dụng" },
      { jp: "座ります", kana: "すわります", rom: "suwarimasu", mean: "ngồi" },
      { jp: "立ちます", kana: "たちます", rom: "tachimasu", mean: "đứng" },
      { jp: "入れます", kana: "いれます", rom: "iremasu", mean: "bỏ vào, cho vào" },
      { jp: "出します", kana: "だします", rom: "dashimasu", mean: "lấy ra" },
      { jp: "まっすぐ", kana: "まっすぐ", rom: "massugu", mean: "thẳng" },
      { jp: "ゆっくり", kana: "ゆっくり", rom: "yukkuri", mean: "chậm rãi" },
      { jp: "すぐ", kana: "すぐ", rom: "sugu", mean: "ngay lập tức" },
      { jp: "信号", kana: "しんごう", rom: "shingou", mean: "đèn tín hiệu" },
      { jp: "交差点", kana: "こうさてん", rom: "kousaten", mean: "ngã tư" }
    ],
    "Bài 15": [
      { jp: "知っています", kana: "しっています", rom: "shitteimasu", mean: "biết" },
      { jp: "住んでいます", kana: "すんでいます", rom: "sundeimasu", mean: "sống, ở" },
      { jp: "働いています", kana: "はたらいています", rom: "hataraiteimasu", mean: "đang làm việc" },
      { jp: "研究しています", kana: "けんきゅうしています", rom: "kenkyuushiteimasu", mean: "đang nghiên cứu" },
      { jp: "太っています", kana: "ふとっています", rom: "futotteimasu", mean: "béo, mập" },
      { jp: "やせています", kana: "やせています", rom: "yaseteimasu", mean: "gầy, ốm" },
      { jp: "お兄さん", kana: "おにいさん", rom: "oniisan", mean: "anh trai" },
      { jp: "お姉さん", kana: "おねえさん", rom: "oneesan", mean: "chị gái" },
      { jp: "弟", kana: "おとうと", rom: "otouto", mean: "em trai" },
      { jp: "妹", kana: "いもうと", rom: "imouto", mean: "em gái" },
      { jp: "お父さん", kana: "おとうさん", rom: "otousan", mean: "bố" },
      { jp: "お母さん", kana: "おかあさん", rom: "okaasan", mean: "mẹ" },
      { jp: "髪", kana: "かみ", rom: "kami", mean: "tóc" },
      { jp: "背", kana: "せ", rom: "se", mean: "chiều cao" },
      { jp: "独身", kana: "どくしん", rom: "dokushin", mean: "độc thân" }
    ],
    "Bài 16": [
      { jp: "乗ります", kana: "のります", rom: "norimasu", mean: "lên (xe, tàu)" },
      { jp: "降ります", kana: "おります", rom: "orimasu", mean: "xuống (xe, tàu)" },
      { jp: "乗り換えます", kana: "のりかえます", rom: "norikaemasu", mean: "chuyển (tàu, xe)" },
      { jp: "浴びます", kana: "あびます", rom: "abimasu", mean: "tắm (vòi hoa sen)" },
      { jp: "押します", kana: "おします", rom: "oshimasu", mean: "ấn, đẩy" },
      { jp: "若い", kana: "わかい", rom: "wakai", mean: "trẻ" },
      { jp: "長い", kana: "ながい", rom: "nagai", mean: "dài" },
      { jp: "短い", kana: "みじかい", rom: "mijikai", mean: "ngắn" },
      { jp: "明るい", kana: "あかるい", rom: "akarui", mean: "sáng" },
      { jp: "暗い", kana: "くらい", rom: "kurai", mean: "tối" },
      { jp: "体", kana: "からだ", rom: "karada", mean: "cơ thể" },
      { jp: "頭", kana: "あたま", rom: "atama", mean: "đầu" },
      { jp: "顔", kana: "かお", rom: "kao", mean: "khuôn mặt" },
      { jp: "目", kana: "め", rom: "me", mean: "mắt" },
      { jp: "耳", kana: "みみ", rom: "mimi", mean: "tai" },
      { jp: "口", kana: "くち", rom: "kuchi", mean: "miệng" },
      { jp: "歯", kana: "は", rom: "ha", mean: "răng" },
      { jp: "お腹", kana: "おなか", rom: "onaka", mean: "bụng" },
      { jp: "足", kana: "あし", rom: "ashi", mean: "chân" },
      { jp: "薬", kana: "くすり", rom: "kusuri", mean: "thuốc" }
    ],
    "Bài 17": [
      { jp: "覚えます", kana: "おぼえます", rom: "oboemasu", mean: "nhớ" },
      { jp: "忘れます", kana: "わすれます", rom: "wasuremasu", mean: "quên" },
      { jp: "なくします", kana: "なくします", rom: "nakushimasu", mean: "làm mất" },
      { jp: "払います", kana: "はらいます", rom: "haraimasu", mean: "trả tiền" },
      { jp: "返します", kana: "かえします", rom: "kaeshimasu", mean: "trả lại" },
      { jp: "出かけます", kana: "でかけます", rom: "dekakemasu", mean: "ra ngoài" },
      { jp: "脱ぎます", kana: "ぬぎます", rom: "nugimasu", mean: "cởi (quần áo)" },
      { jp: "持っていきます", kana: "もっていきます", rom: "motteikimasu", mean: "mang đi" },
      { jp: "持ってきます", kana: "もってきます", rom: "mottekimasu", mean: "mang đến" },
      { jp: "心配します", kana: "しんぱいします", rom: "shinpaishimasu", mean: "lo lắng" },
      { jp: "残業します", kana: "ざんぎょうします", rom: "zangyoushimasu", mean: "làm thêm giờ" },
      { jp: "大丈夫", kana: "だいじょうぶ", rom: "daijoubu", mean: "không sao" },
      { jp: "危ない", kana: "あぶない", rom: "abunai", mean: "nguy hiểm" },
      { jp: "問題", kana: "もんだい", rom: "mondai", mean: "vấn đề, câu hỏi" },
      { jp: "答え", kana: "こたえ", rom: "kotae", mean: "câu trả lời" },
      { jp: "禁煙", kana: "きんえん", rom: "kin'en", mean: "cấm hút thuốc" }
    ],
    "Bài 18": [
      { jp: "できます", kana: "できます", rom: "dekimasu", mean: "có thể" },
      { jp: "洗います", kana: "あらいます", rom: "araimasu", mean: "rửa, giặt" },
      { jp: "弾きます", kana: "ひきます", rom: "hikimasu", mean: "chơi (đàn)" },
      { jp: "歌います", kana: "うたいます", rom: "utaimasu", mean: "hát" },
      { jp: "集めます", kana: "あつめます", rom: "atsumemasu", mean: "sưu tập, thu thập" },
      { jp: "捨てます", kana: "すてます", rom: "sutemasu", mean: "vứt, bỏ" },
      { jp: "換えます", kana: "かえます", rom: "kaemasu", mean: "đổi" },
      { jp: "運転します", kana: "うんてんします", rom: "untenshimasu", mean: "lái xe" },
      { jp: "予約します", kana: "よやくします", rom: "yoyakushimasu", mean: "đặt trước" },
      { jp: "ピアノ", kana: "ぴあの", rom: "piano", mean: "đàn piano" },
      { jp: "趣味", kana: "しゅみ", rom: "shumi", mean: "sở thích" },
      { jp: "日記", kana: "にっき", rom: "nikki", mean: "nhật ký" },
      { jp: "お祈り", kana: "おいのり", rom: "oinori", mean: "cầu nguyện" },
      { jp: "動物", kana: "どうぶつ", rom: "doubutsu", mean: "động vật" },
      { jp: "馬", kana: "うま", rom: "uma", mean: "ngựa" }
    ],
    "Bài 19": [
      { jp: "登ります", kana: "のぼります", rom: "noborimasu", mean: "leo, trèo" },
      { jp: "泊まります", kana: "とまります", rom: "tomarimasu", mean: "nghỉ trọ" },
      { jp: "掃除します", kana: "そうじします", rom: "soujishimasu", mean: "dọn dẹp" },
      { jp: "洗濯します", kana: "せんたくします", rom: "sentakushimasu", mean: "giặt giũ" },
      { jp: "練習します", kana: "れんしゅうします", rom: "renshuushimasu", mean: "luyện tập" },
      { jp: "なります", kana: "なります", rom: "narimasu", mean: "trở nên" },
      { jp: "眠い", kana: "ねむい", rom: "nemui", mean: "buồn ngủ" },
      { jp: "強い", kana: "つよい", rom: "tsuyoi", mean: "mạnh, khỏe" },
      { jp: "弱い", kana: "よわい", rom: "yowai", mean: "yếu" },
      { jp: "調子がいい", kana: "ちょうしがいい", rom: "choushi ga ii", mean: "tình trạng tốt" },
      { jp: "お風呂", kana: "おふろ", rom: "ofuro", mean: "bồn tắm" },
      { jp: "柔道", kana: "じゅうどう", rom: "juudou", mean: "nhu đạo" },
      { jp: "生け花", kana: "いけばな", rom: "ikebana", mean: "cắm hoa" },
      { jp: "茶道", kana: "さどう", rom: "sadou", mean: "trà đạo" }
    ],
    "Bài 20": [
      { jp: "要ります", kana: "いります", rom: "irimasu", mean: "cần" },
      { jp: "調べます", kana: "しらべます", rom: "shirabemasu", mean: "tra, điều tra" },
      { jp: "直します", kana: "なおします", rom: "naoshimasu", mean: "sửa" },
      { jp: "修理します", kana: "しゅうりします", rom: "shuurishimasu", mean: "sửa chữa" },
      { jp: "ていねい", kana: "ていねい", rom: "teinei", mean: "lịch sự" },
      { jp: "すてき", kana: "すてき", rom: "suteki", mean: "tuyệt vời" },
      { jp: "いろいろ", kana: "いろいろ", rom: "iroiro", mean: "nhiều loại" },
      { jp: "仕事", kana: "しごと", rom: "shigoto", mean: "công việc" },
      { jp: "コート", kana: "こーと", rom: "kooto", mean: "áo khoác" },
      { jp: "スカート", kana: "すかーと", rom: "sukaato", mean: "váy" },
      { jp: "セーター", kana: "せーたー", rom: "seetaa", mean: "áo len" },
      { jp: "シャツ", kana: "しゃつ", rom: "shatsu", mean: "áo sơ mi" },
      { jp: "ジーンズ", kana: "じーんず", rom: "jiinzu", mean: "quần jean" },
      { jp: "靴", kana: "くつ", rom: "kutsu", mean: "giày" },
      { jp: "帽子", kana: "ぼうし", rom: "boushi", mean: "mũ" },
      { jp: "めがね", kana: "めがね", rom: "megane", mean: "kính" }
    ],
    "Bài 21": [
      { jp: "思います", kana: "おもいます", rom: "omoimasu", mean: "nghĩ" },
      { jp: "言います", kana: "いいます", rom: "iimasu", mean: "nói" },
      { jp: "足ります", kana: "たります", rom: "tarimasu", mean: "đủ" },
      { jp: "勝ちます", kana: "かちます", rom: "kachimasu", mean: "thắng" },
      { jp: "負けます", kana: "まけます", rom: "makemasu", mean: "thua" },
      { jp: "役に立ちます", kana: "やくにたちます", rom: "yaku ni tachimasu", mean: "có ích" },
      { jp: "試合", kana: "しあい", rom: "shiai", mean: "trận đấu" },
      { jp: "政治", kana: "せいじ", rom: "seiji", mean: "chính trị" },
      { jp: "経済", kana: "けいざい", rom: "keizai", mean: "kinh tế" },
      { jp: "社会", kana: "しゃかい", rom: "shakai", mean: "xã hội" },
      { jp: "ニュース", kana: "にゅーす", rom: "nyuusu", mean: "tin tức" },
      { jp: "意見", kana: "いけん", rom: "iken", mean: "ý kiến" },
      { jp: "話", kana: "はなし", rom: "hanashi", mean: "câu chuyện" },
      { jp: "自然", kana: "しぜん", rom: "shizen", mean: "thiên nhiên" },
      { jp: "夢", kana: "ゆめ", rom: "yume", mean: "giấc mơ" }
    ],
    "Bài 22": [
      { jp: "着ます", kana: "きます", rom: "kimasu", mean: "mặc (áo)" },
      { jp: "履きます", kana: "はきます", rom: "hakimasu", mean: "đi (giày, quần)" },
      { jp: "かぶります", kana: "かぶります", rom: "kaburimasu", mean: "đội (mũ)" },
      { jp: "かけます", kana: "かけます", rom: "kakemasu", mean: "đeo (kính)" },
      { jp: "生まれます", kana: "うまれます", rom: "umaremasu", mean: "được sinh ra" },
      { jp: "コンサート", kana: "こんさーと", rom: "konsaato", mean: "buổi hòa nhạc" },
      { jp: "祭り", kana: "まつり", rom: "matsuri", mean: "lễ hội" },
      { jp: "旅行", kana: "りょこう", rom: "ryokou", mean: "du lịch" },
      { jp: "彼氏", kana: "かれし", rom: "kareshi", mean: "bạn trai" },
      { jp: "彼女", kana: "かのじょ", rom: "kanojo", mean: "bạn gái" },
      { jp: "色", kana: "いろ", rom: "iro", mean: "màu sắc" },
      { jp: "デザイン", kana: "でざいん", rom: "dezain", mean: "thiết kế" },
      { jp: "お土産", kana: "おみやげ", rom: "omiyage", mean: "quà lưu niệm" }
    ],
    "Bài 23": [
      { jp: "聞きます", kana: "ききます", rom: "kikimasu", mean: "hỏi" },
      { jp: "回します", kana: "まわします", rom: "mawashimasu", mean: "xoay, quay" },
      { jp: "引きます", kana: "ひきます", rom: "hikimasu", mean: "kéo" },
      { jp: "変えます", kana: "かえます", rom: "kaemasu", mean: "thay đổi" },
      { jp: "触ります", kana: "さわります", rom: "sawarimasu", mean: "chạm, sờ" },
      { jp: "出ます", kana: "でます", rom: "demasu", mean: "ra (đi ra)" },
      { jp: "動きます", kana: "うごきます", rom: "ugokimasu", mean: "di chuyển" },
      { jp: "歩きます", kana: "あるきます", rom: "arukimasu", mean: "đi bộ" },
      { jp: "渡ります", kana: "わたります", rom: "watarimasu", mean: "băng qua" },
      { jp: "気をつけます", kana: "きをつけます", rom: "ki o tsukemasu", mean: "cẩn thận" },
      { jp: "建物", kana: "たてもの", rom: "tatemono", mean: "tòa nhà" },
      { jp: "道", kana: "みち", rom: "michi", mean: "đường" },
      { jp: "橋", kana: "はし", rom: "hashi", mean: "cầu" },
      { jp: "角", kana: "かど", rom: "kado", mean: "góc" }
    ],
    "Bài 24": [
      { jp: "くれます", kana: "くれます", rom: "kuremasu", mean: "cho (tôi)" },
      { jp: "連れていきます", kana: "つれていきます", rom: "tsureteikimasu", mean: "dẫn đi" },
      { jp: "送ります", kana: "おくります", rom: "okurimasu", mean: "tiễn" },
      { jp: "紹介します", kana: "しょうかいします", rom: "shoukaishimasu", mean: "giới thiệu" },
      { jp: "案内します", kana: "あんないします", rom: "annaishimasu", mean: "hướng dẫn" },
      { jp: "説明します", kana: "せつめいします", rom: "setsumeishimasu", mean: "giải thích" },
      { jp: "母", kana: "はは", rom: "haha", mean: "mẹ (mình)" },
      { jp: "父", kana: "ちち", rom: "chichi", mean: "bố (mình)" },
      { jp: "おじいさん", kana: "おじいさん", rom: "ojiisan", mean: "ông" },
      { jp: "おばあさん", kana: "おばあさん", rom: "obaasan", mean: "bà" },
      { jp: "準備", kana: "じゅんび", rom: "junbi", mean: "chuẩn bị" },
      { jp: "引っ越し", kana: "ひっこし", rom: "hikkoshi", mean: "chuyển nhà" }
    ],
    "Bài 25": [
      { jp: "考えます", kana: "かんがえます", rom: "kangaemasu", mean: "suy nghĩ" },
      { jp: "着きます", kana: "つきます", rom: "tsukimasu", mean: "đến nơi" },
      { jp: "届きます", kana: "とどきます", rom: "todokimasu", mean: "được giao đến" },
      { jp: "なくなります", kana: "なくなります", rom: "nakunarimasu", mean: "hết, mất đi" },
      { jp: "困ります", kana: "こまります", rom: "komarimasu", mean: "gặp khó khăn" },
      { jp: "出します", kana: "だします", rom: "dashimasu", mean: "nộp, gửi" },
      { jp: "塗ります", kana: "ぬります", rom: "nurimasu", mean: "bôi, sơn" },
      { jp: "田舎", kana: "いなか", rom: "inaka", mean: "quê, nông thôn" },
      { jp: "チャンス", kana: "ちゃんす", rom: "chansu", mean: "cơ hội" },
      { jp: "億", kana: "おく", rom: "oku", mean: "trăm triệu" },
      { jp: "もし", kana: "もし", rom: "moshi", mean: "nếu" },
      { jp: "いくら～ても", kana: "いくら～ても", rom: "ikura ~ temo", mean: "dù... thế nào đi nữa" },
      { jp: "それなら", kana: "それなら", rom: "sorenara", mean: "nếu vậy thì" }
    ]
  },
  "N4": {
    "Bài 26": [
      { jp: "見ます", kana: "みます", rom: "mimasu", mean: "xem, khám bệnh" },
      { jp: "探します", kana: "さがします", rom: "sagashimasu", mean: "tìm, tìm kiếm" },
      { jp: "遅れます", kana: "おくれます", rom: "okuremasu", mean: "chậm trễ" },
      { jp: "間に合います", kana: "まにあいます", rom: "maniaimasu", mean: "kịp thời gian" },
      { jp: "やります", kana: "やります", rom: "yarimasu", mean: "làm" },
      { jp: "拾います", kana: "ひろいます", rom: "hiroimasu", mean: "nhặt" },
      { jp: "連絡します", kana: "れんらくします", rom: "renrakushimasu", mean: "liên lạc" },
      { jp: "気分がいい", kana: "きぶんがいい", rom: "kibun ga ii", mean: "tâm trạng tốt, dễ chịu" },
      { jp: "気分が悪い", kana: "きぶんがわるい", rom: "kibun ga warui", mean: "tâm trạng tồi tệ, khó chịu" },
      { jp: "運動会", kana: "うんどうかい", rom: "undoukai", mean: "hội thi thể thao" },
      { jp: "盆踊り", kana: "ぼんおどり", rom: "bon-odori", mean: "điệu múa Bon" },
      { jp: "フリーマーケット", kana: "ふりーまーけっと", rom: "furiimaketto", mean: "chợ trời" },
      { jp: "場所", kana: "ばしょ", rom: "basho", mean: "địa điểm" },
      { jp: "ボランティア", kana: "ぼらんてぃあ", rom: "borantia", mean: "tình nguyện viên" },
      { jp: "財布", kana: "さいふ", rom: "saifu", mean: "cái ví" },
      { jp: "ごみ", kana: "ごみ", rom: "gomi", mean: "rác" }
    ],
    "Bài 27": [
      { jp: "飼います", kana: "かいます", rom: "kaimasu", mean: "nuôi (động vật)" },
      { jp: "走ります", kana: "はしります", rom: "hashirimasu", mean: "chạy" },
      { jp: "見えます", kana: "みえます", rom: "miemasu", mean: "nhìn thấy được" },
      { jp: "聞こえます", kana: "きこえます", rom: "kikoemasu", mean: "nghe thấy được" },
      { jp: "できます", kana: "できます", rom: "dekimasu", mean: "được xây dựng lên, hoàn thành" },
      { jp: "開きます", kana: "ひらきます", rom: "hirakimasu", mean: "mở (lớp học...)" },
      { jp: "心配", kana: "しんぱい", rom: "shinpai", mean: "lo lắng" },
      { jp: "ペット", kana: "ぺっと", rom: "petto", mean: "thú cưng" },
      { jp: "鳥", kana: "とり", rom: "tori", mean: "chim" },
      { jp: "声", kana: "こえ", rom: "koe", mean: "giọng nói, tiếng kêu" },
      { jp: "波", kana: "なみ", rom: "nami", mean: "sóng" },
      { jp: "花火", kana: "はなび", rom: "hanabi", mean: "pháo hoa" },
      { jp: "道具", kana: "どうぐ", rom: "dougu", mean: "dụng cụ, đồ nghề" },
      { jp: "クリーニング", kana: "くりーにんぐ", rom: "kuriiningu", mean: "giặt ủi" },
      { jp: "家", kana: "いえ", rom: "ie", mean: "nhà, căn nhà" }
    ],
    "Bài 28": [
      { jp: "歩きます", kana: "あるきます", rom: "arukimasu", mean: "đi bộ" },
      { jp: "走ります", kana: "はしります", rom: "hashirimasu", mean: "chạy" },
      { jp: "片付けます", kana: "かたづけます", rom: "katazukemasu", mean: "dọn dẹp" },
      { jp: "続けます", kana: "つづけます", rom: "tsuzukemasu", mean: "tiếp tục" },
      { jp: "見つけます", kana: "みつけます", rom: "mitsukemasu", mean: "tìm thấy" },
      { jp: "届けます", kana: "とどけます", rom: "todokemasu", mean: "giao, chuyển đến" },
      { jp: "入院します", kana: "にゅういんします", rom: "nyuuinshimasu", mean: "nhập viện" },
      { jp: "退院します", kana: "たいいんします", rom: "taiinshimasu", mean: "xuất viện" },
      { jp: "お見舞い", kana: "おみまい", rom: "omimai", mean: "thăm bệnh" },
      { jp: "毎日", kana: "まいにち", rom: "mainichi", mean: "hàng ngày" },
      { jp: "将来", kana: "しょうらい", rom: "shourai", mean: "tương lai" },
      { jp: "経験", kana: "けいけん", rom: "keiken", mean: "kinh nghiệm" },
      { jp: "力", kana: "ちから", rom: "chikara", mean: "sức mạnh" },
      { jp: "人気", kana: "にんき", rom: "ninki", mean: "nổi tiếng, được yêu thích" }
    ],
    "Bài 29": [
      { jp: "落とします", kana: "おとします", rom: "otoshimasu", mean: "làm rơi" },
      { jp: "見つかります", kana: "みつかります", rom: "mitsukarimasu", mean: "được tìm thấy" },
      { jp: "壊れます", kana: "こわれます", rom: "kowaremasu", mean: "bị hỏng" },
      { jp: "割れます", kana: "われます", rom: "waremasu", mean: "bị vỡ" },
      { jp: "折れます", kana: "おれます", rom: "oremasu", mean: "bị gãy" },
      { jp: "破れます", kana: "やぶれます", rom: "yaburemasu", mean: "bị rách" },
      { jp: "汚れます", kana: "よごれます", rom: "yogoremasu", mean: "bị bẩn" },
      { jp: "つきます", kana: "つきます", rom: "tsukimasu", mean: "bật (đèn)" },
      { jp: "消えます", kana: "きえます", rom: "kiemasu", mean: "tắt (đèn)" },
      { jp: "開きます", kana: "あきます", rom: "akimasu", mean: "mở (tự)" },
      { jp: "閉まります", kana: "しまります", rom: "shimarimasu", mean: "đóng (tự)" },
      { jp: "止まります", kana: "とまります", rom: "tomarimasu", mean: "dừng (tự)" },
      { jp: "間違えます", kana: "まちがえます", rom: "machigaemasu", mean: "nhầm lẫn" },
      { jp: "取り替えます", kana: "とりかえます", rom: "torikaemasu", mean: "thay thế" }
    ],
    "Bài 30": [
      { jp: "貼ります", kana: "はります", rom: "harimasu", mean: "dán" },
      { jp: "掛けます", kana: "かけます", rom: "kakemasu", mean: "treo" },
      { jp: "飾ります", kana: "かざります", rom: "kazarimasu", mean: "trang trí" },
      { jp: "並べます", kana: "ならべます", rom: "narabemasu", mean: "xếp, bày" },
      { jp: "植えます", kana: "うえます", rom: "uemasu", mean: "trồng" },
      { jp: "戻します", kana: "もどします", rom: "modoshimasu", mean: "trả lại chỗ cũ" },
      { jp: "まとめます", kana: "まとめます", rom: "matomemasu", mean: "tổng hợp" },
      { jp: "しまいます", kana: "しまいます", rom: "shimaimasu", mean: "cất đi" },
      { jp: "決めます", kana: "きめます", rom: "kimemasu", mean: "quyết định" },
      { jp: "壁", kana: "かべ", rom: "kabe", mean: "tường" },
      { jp: "カレンダー", kana: "かれんだー", rom: "karendaa", mean: "lịch" },
      { jp: "ポスター", kana: "ぽすたー", rom: "posutaa", mean: "áp phích" }
    ],
    "Bài 31": [
      { jp: "始めます", kana: "はじめます", rom: "hajimemasu", mean: "bắt đầu" },
      { jp: "増えます", kana: "ふえます", rom: "fuemasu", mean: "tăng" },
      { jp: "減ります", kana: "へります", rom: "herimasu", mean: "giảm" },
      { jp: "上がります", kana: "あがります", rom: "agarimasu", mean: "tăng lên" },
      { jp: "下がります", kana: "さがります", rom: "sagarimasu", mean: "giảm xuống" },
      { jp: "入学します", kana: "にゅうがくします", rom: "nyuugakushimasu", mean: "nhập học" },
      { jp: "卒業します", kana: "そつぎょうします", rom: "sotsugyoushimasu", mean: "tốt nghiệp" },
      { jp: "留学します", kana: "りゅうがくします", rom: "ryuugakushimasu", mean: "du học" },
      { jp: "つもり", kana: "つもり", rom: "tsumori", mean: "dự định" },
      { jp: "予定", kana: "よてい", rom: "yotei", mean: "kế hoạch" },
      { jp: "まだ", kana: "まだ", rom: "mada", mean: "vẫn chưa" },
      { jp: "これから", kana: "これから", rom: "korekara", mean: "từ bây giờ" }
    ],
    "Bài 32": [
      { jp: "運動します", kana: "うんどうします", rom: "undoushimasu", mean: "tập thể dục" },
      { jp: "成功します", kana: "せいこうします", rom: "seikoushimasu", mean: "thành công" },
      { jp: "失敗します", kana: "しっぱいします", rom: "shippaishimasu", mean: "thất bại" },
      { jp: "合格します", kana: "ごうかくします", rom: "goukakushimasu", mean: "đỗ, đạt" },
      { jp: "痩せます", kana: "やせます", rom: "yasemasu", mean: "gầy đi" },
      { jp: "太ります", kana: "ふとります", rom: "futorimasu", mean: "béo lên" },
      { jp: "ダイエット", kana: "だいえっと", rom: "daietto", mean: "ăn kiêng" },
      { jp: "味", kana: "あじ", rom: "aji", mean: "vị" },
      { jp: "においい", kana: "におい", rom: "nioi", mean: "mùi" },
      { jp: "無理", kana: "むり", rom: "muri", mean: "quá sức, vô lý" },
      { jp: "十分", kana: "じゅうぶん", rom: "juubun", mean: "đủ" },
      { jp: "普通", kana: "ふつう", rom: "futsuu", mean: "bình thường" }
    ],
    "Bài 33": [
      { jp: "逃げます", kana: "にげます", rom: "nigemasu", mean: "chạy trốn" },
      { jp: "騒ぎます", kana: "さわぎます", rom: "sawagimasu", mean: "gây ồn ào" },
      { jp: "諦めます", kana: "あきらめます", rom: "akiramemasu", mean: "từ bỏ" },
      { jp: "投げます", kana: "なげます", rom: "nagemasu", mean: "ném" },
      { jp: "守ります", kana: "まもります", rom: "mamorimasu", mean: "giữ, bảo vệ" },
      { jp: "始まります", kana: "はじまります", rom: "hajimarimasu", mean: "bắt đầu (tự)" },
      { jp: "届きます", kana: "とどきます", rom: "todokimasu", mean: "được giao" },
      { jp: "命令", kana: "めいれい", rom: "meirei", mean: "mệnh lệnh" },
      { jp: "指示", kana: "しじ", rom: "shiji", mean: "chỉ thị" },
      { jp: "注意", kana: "ちゅうい", rom: "chuui", mean: "chú ý" },
      { jp: "規則", kana: "きそく", rom: "kisoku", mean: "quy tắc" },
      { jp: "マーク", kana: "まーく", rom: "maaku", mean: "ký hiệu" }
    ],
    "Bài 34": [
      { jp: "磨きます", kana: "みがきます", rom: "migakimasu", mean: "đánh (răng)" },
      { jp: "組み立てます", kana: "くみたてます", rom: "kumitatemasu", mean: "lắp ráp" },
      { jp: "折ります", kana: "おります", rom: "orimasu", mean: "gấp, bẻ" },
      { jp: "気がつきます", kana: "きがつきます", rom: "ki ga tsukimasu", mean: "nhận ra" },
      { jp: "付けます", kana: "つけます", rom: "tsukemasu", mean: "gắn, đính" },
      { jp: "見つかります", kana: "みつかります", rom: "mitsukarimasu", mean: "tìm thấy" },
      { jp: "形", kana: "かたち", rom: "katachi", mean: "hình dạng" },
      { jp: "習慣", kana: "しゅうかん", rom: "shuukan", mean: "thói quen" },
      { jp: "お礼", kana: "おれい", rom: "orei", mean: "lời cảm ơn" },
      { jp: "お知らせ", kana: "おしらせ", rom: "oshirase", mean: "thông báo" },
      { jp: "順番", kana: "じゅんばん", rom: "junban", mean: "thứ tự" }
    ],
    "Bài 35": [
      { jp: "咲きます", kana: "さきます", rom: "sakimasu", mean: "nở (hoa)" },
      { jp: "変わります", kana: "かわります", rom: "kawarimasu", mean: "thay đổi (tự)" },
      { jp: "困ります", kana: "こまります", rom: "komarimasu", mean: "gặp khó khăn" },
      { jp: "つけます", kana: "つけます", rom: "tsukemasu", mean: "ngâm" },
      { jp: "混ぜます", kana: "まぜます", rom: "mazemasu", mean: "trộn" },
      { jp: "皮をむきます", kana: "かわをむきます", rom: "kawa o mukimasu", mean: "gọt vỏ" },
      { jp: "おもちゃ", kana: "おもちゃ", rom: "omocha", mean: "đồ chơi" },
      { jp: "嘘", kana: "うそ", rom: "uso", mean: "nói dối" },
      { jp: "お湯", kana: "おゆ", rom: "oyu", mean: "nước nóng" },
      { jp: "材料", kana: "ざいりょう", rom: "zairyou", mean: "nguyên liệu" },
      { jp: "量", kana: "りょう", rom: "ryou", mean: "lượng" },
      { jp: "やっと", kana: "やっと", rom: "yatto", mean: "cuối cùng cũng" }
    ],
    "Bài 36": [
      { jp: "頑張ります", kana: "がんばります", rom: "ganbarimasu", mean: "cố gắng" },
      { jp: "取ります", kana: "とります", rom: "torimasu", mean: "lấy, giành" },
      { jp: "直します", kana: "なおします", rom: "naoshimasu", mean: "sửa" },
      { jp: "伝えます", kana: "つたえます", rom: "tsutaemasu", mean: "truyền đạt" },
      { jp: "注意します", kana: "ちゅういします", rom: "chuuishimasu", mean: "chú ý" },
      { jp: "安全", kana: "あんぜん", rom: "anzen", mean: "an toàn" },
      { jp: "複雑", kana: "ふくざつ", rom: "fukuzatsu", mean: "phức tạp" },
      { jp: "邪魔", kana: "じゃま", rom: "jama", mean: "cản trở" },
      { jp: "目的", kana: "もくてき", rom: "mokuteki", mean: "mục đích" },
      { jp: "スピーチ", kana: "すぴーち", rom: "supiichi", mean: "bài phát biểu" },
      { jp: "間違い", kana: "まちがい", rom: "machigai", mean: "sai lầm" },
      { jp: "選手", kana: "せんしゅ", rom: "senshu", mean: "vận động viên" }
    ],
    "Bài 37": [
      { jp: "褒めます", kana: "ほめます", rom: "homemasu", mean: "khen" },
      { jp: "叱ります", kana: "しかります", rom: "shikarimasu", mean: "mắng" },
      { jp: "誘います", kana: "さそいます", rom: "sasoimasu", mean: "rủ, mời" },
      { jp: "頼みます", kana: "たのみます", rom: "tanomimasu", mean: "nhờ" },
      { jp: "注意します", kana: "ちゅういします", rom: "chuuishimasu", mean: "nhắc nhở" },
      { jp: "取ります", kana: "とります", rom: "torimasu", mean: "lấy, trộm" },
      { jp: "踏みます", kana: "ふみます", rom: "fumimasu", mean: "giẫm, đạp" },
      { jp: "壊します", kana: "こわします", rom: "kowashimasu", mean: "phá hỏng" },
      { jp: "汚します", kana: "よごします", rom: "yogoshimasu", mean: "làm bẩn" },
      { jp: "行われます", kana: "おこなわれます", rom: "okonawaremasu", mean: "được tổ chức" },
      { jp: "見つかります", kana: "みつかります", rom: "mitsukarimasu", mean: "bị phát hiện" },
      { jp: "情報", kana: "じょうほう", rom: "jouhou", mean: "thông tin" },
      { jp: "文化", kana: "ぶんか", rom: "bunka", mean: "văn hóa" },
      { jp: "習慣", kana: "しゅうかん", rom: "shuukan", mean: "tập quán" }
    ],
    "Bài 38": [
      { jp: "楽しみます", kana: "たのしみます", rom: "tanoshimimasu", mean: "thưởng thức" },
      { jp: "驚きます", kana: "おどろきます", rom: "odorokimasu", mean: "ngạc nhiên" },
      { jp: "安心します", kana: "あんしんします", rom: "anshinshimasu", mean: "yên tâm" },
      { jp: "がっかりします", kana: "がっかりします", rom: "gakkarishimasu", mean: "thất vọng" },
      { jp: "びっくりします", kana: "びっくりします", rom: "bikkurishimasu", mean: "giật mình" },
      { jp: "怖い", kana: "こわい", rom: "kowai", mean: "sợ hãi" },
      { jp: "うれしい", kana: "うれしい", rom: "ureshii", mean: "vui mừng" },
      { jp: "悲しい", kana: "かなしい", rom: "kanashii", mean: "buồn" },
      { jp: "恥ずかしい", kana: "はずかしい", rom: "hazukashii", mean: "xấu hổ" },
      { jp: "懐かしい", kana: "なつかしい", rom: "natsukashii", mean: "nhớ nhung" },
      { jp: "気持ち", kana: "きもち", rom: "kimochi", mean: "tâm trạng, cảm giác" },
      { jp: "教育", kana: "きょういく", rom: "kyouiku", mean: "giáo dục" },
      { jp: "歴史", kana: "れきし", rom: "rekishi", mean: "lịch sử" },
      { jp: "地理", kana: "ちり", rom: "chiri", mean: "địa lý" },
      { jp: "数学", kana: "すうがく", rom: "suugaku", mean: "toán học" }
    ],
    "Bài 39": [
      { jp: "起こします", kana: "おこします", rom: "okoshimasu", mean: "đánh thức" },
      { jp: "感動します", kana: "かんどうします", rom: "kandoushimasu", mean: "cảm động" },
      { jp: "心配します", kana: "しんぱいします", rom: "shinpaishimasu", mean: "lo lắng" },
      { jp: "怒ります", kana: "おこります", rom: "okorimasu", mean: "giận" },
      { jp: "泣きます", kana: "なきます", rom: "nakimasu", mean: "khóc" },
      { jp: "笑います", kana: "わらいます", rom: "waraimasu", mean: "cười" },
      { jp: "乾きます", kana: "かわきます", rom: "kawakimasu", mean: "khô" },
      { jp: "濡れます", kana: "ぬれます", rom: "nuremasu", mean: "ướt" },
      { jp: "滑ります", kana: "すべります", rom: "suberimasu", mean: "trượt" },
      { jp: "地震", kana: "じしん", rom: "jishin", mean: "động đất" },
      { jp: "台風", kana: "たいふう", rom: "taifuu", mean: "bão" },
      { jp: "火事", kana: "かじ", rom: "kaji", mean: "hỏa hoạn" },
      { jp: "事故", kana: "じこ", rom: "jiko", mean: "tai nạn" },
      { jp: "原因", kana: "げんいん", rom: "gen'in", mean: "nguyên nhân" }
    ],
    "Bài 40": [
      { jp: "数えます", kana: "かぞえます", rom: "kazoemasu", mean: "đếm" },
      { jp: "測ります", kana: "はかります", rom: "hakarimasu", mean: "đo" },
      { jp: "確かめます", kana: "たしかめます", rom: "tashikamemasu", mean: "xác nhận" },
      { jp: "合います", kana: "あいます", rom: "aimasu", mean: "vừa, hợp" },
      { jp: "出席します", kana: "しゅっせきします", rom: "shussekishimasu", mean: "tham dự" },
      { jp: "必要", kana: "ひつよう", rom: "hitsuyou", mean: "cần thiết" },
      { jp: "特別", kana: "とくべつ", rom: "tokubetsu", mean: "đặc biệt" },
      { jp: "正確", kana: "せいかく", rom: "seikaku", mean: "chính xác" },
      { jp: "急", kana: "きゅう", rom: "kyuu", mean: "gấp, đột ngột" },
      { jp: "連休", kana: "れんきゅう", rom: "renkyuu", mean: "kỳ nghỉ dài" },
      { jp: "届け", kana: "とどけ", rom: "todoke", mean: "đơn xin, giấy báo" }
    ],
    "Bài 41": [
      { jp: "いただきます", kana: "いただきます", rom: "itadakimasu", mean: "nhận (khiêm nhường)" },
      { jp: "くださいます", kana: "くださいます", rom: "kudasaimasu", mean: "cho (kính ngữ)" },
      { jp: "やります", kana: "やります", rom: "yarimasu", mean: "cho (dưới)" },
      { jp: "お返しします", kana: "おかえしします", rom: "okaeshishimasu", mean: "gửi lại" },
      { jp: "呼びます", kana: "よびます", rom: "yobimasu", mean: "gọi" },
      { jp: "選びます", kana: "えらびます", rom: "erabimasu", mean: "chọn" },
      { jp: "気持ち", kana: "きもち", rom: "kimochi", mean: "tâm trạng" },
      { jp: "お祝い", kana: "おいわい", rom: "oiwai", mean: "lễ mừng" },
      { jp: "入学祝い", kana: "にゅうがくいわい", rom: "nyuugaku iwai", mean: "quà mừng nhập học" },
      { jp: "お見舞い", kana: "おみまい", rom: "omimai", mean: "quà thăm bệnh" },
      { jp: "お年玉", kana: "おとしだま", rom: "otoshidama", mean: "tiền mừng tuổi" }
    ],
    "Bài 42": [
      { jp: "包みます", kana: "つつみます", rom: "tsutsumimasu", mean: "gói" },
      { jp: "沸かします", kana: "わかします", rom: "wakashimasu", mean: "đun sôi" },
      { jp: "混ぜます", kana: "まぜます", rom: "mazemasu", mean: "trộn" },
      { jp: "計算します", kana: "けいさんします", rom: "keisanshimasu", mean: "tính toán" },
      { jp: "研究します", kana: "けんきゅうします", rom: "kenkyuushimasu", mean: "nghiên cứu" },
      { jp: "発明します", kana: "はつめいします", rom: "hatsumeishimasu", mean: "phát minh" },
      { jp: "発見します", kana: "はっけんします", rom: "hakkenshimasu", mean: "phát hiện" },
      { jp: "利用します", kana: "りようします", rom: "riyoushimasu", mean: "sử dụng, tận dụng" },
      { jp: "技術", kana: "ぎじゅつ", rom: "gijutsu", mean: "kỹ thuật" },
      { jp: "産業", kana: "さんぎょう", rom: "sangyou", mean: "công nghiệp" },
      { jp: "製品", kana: "せいひん", rom: "seihin", mean: "sản phẩm" },
      { jp: "原料", kana: "げんりょう", rom: "genryou", mean: "nguyên liệu" },
      { jp: "世界", kana: "せかい", rom: "sekai", mean: "thế giới" }
    ],
    "Bài 43": [
      { jp: "似合います", kana: "にあいます", rom: "niaimasu", mean: "hợp, phù hợp" },
      { jp: "足ります", kana: "たります", rom: "tarimasu", mean: "đủ" },
      { jp: "役に立ちます", kana: "やくにたちます", rom: "yaku ni tachimasu", mean: "có ích" },
      { jp: "急ぎます", kana: "いそぎます", rom: "isogimasu", mean: "vội" },
      { jp: "人口", kana: "じんこう", rom: "jinkou", mean: "dân số" },
      { jp: "面積", kana: "めんせき", rom: "menseki", mean: "diện tích" },
      { jp: "輸出", kana: "ゆしゅつ", rom: "yushutsu", mean: "xuất khẩu" },
      { jp: "輸入", kana: "ゆにゅう", rom: "yunyuu", mean: "nhập khẩu" },
      { jp: "品物", kana: "しなもの", rom: "shinamono", mean: "hàng hóa" },
      { jp: "値段", kana: "ねだん", rom: "nedan", mean: "giá cả" },
      { jp: "物価", kana: "ぶっか", rom: "bukka", mean: "vật giá" },
      { jp: "生活", kana: "せいかつ", rom: "seikatsu", mean: "cuộc sống" }
    ],
    "Bài 44": [
      { jp: "泣きます", kana: "なきます", rom: "nakimasu", mean: "khóc" },
      { jp: "笑います", kana: "わらいます", rom: "waraimasu", mean: "cười" },
      { jp: "変えます", kana: "かえます", rom: "kaemasu", mean: "thay đổi" },
      { jp: "簡単", kana: "かんたん", rom: "kantan", mean: "đơn giản" },
      { jp: "複雑", kana: "ふくざつ", rom: "fukuzatsu", mean: "phức tạp" },
      { jp: "柔らかい", kana: "やわらかい", rom: "yawarakai", mean: "mềm" },
      { jp: "硬い", kana: "かたい", rom: "katai", mean: "cứng" },
      { jp: "太い", kana: "ふとい", rom: "futoi", mean: "béo, to" },
      { jp: "細い", kana: "ほそい", rom: "hosoi", mean: "mảnh, gầy" },
      { jp: "厚い", kana: "あつい", rom: "atsui", mean: "dày" },
      { jp: "薄い", kana: "うすい", rom: "usui", mean: "mỏng, nhạt" },
      { jp: "きつい", kana: "きつい", rom: "kitsui", mean: "chật" },
      { jp: "ぶかぶか", kana: "ぶかぶか", rom: "bukabuka", mean: "rộng thùng thình" }
    ],
    "Bài 45": [
      { jp: "気をつけます", kana: "きをつけます", rom: "ki o tsukemasu", mean: "chú ý" },
      { jp: "電話します", kana: "でんわします", rom: "denwashimasu", mean: "gọi điện" },
      { jp: "参加します", kana: "さんかします", rom: "sankashimasu", mean: "tham gia" },
      { jp: "遅刻します", kana: "ちこくします", rom: "chikokushimasu", mean: "đi muộn" },
      { jp: "危険", kana: "きけん", rom: "kiken", mean: "nguy hiểm" },
      { jp: "影響", kana: "えいきょう", rom: "eikyou", mean: "ảnh hưởng" },
      { jp: "関係", kana: "かんけい", rom: "kankei", mean: "quan hệ" },
      { jp: "場合", kana: "ばあい", rom: "baai", mean: "trường hợp" },
      { jp: "できるだけ", kana: "できるだけ", rom: "dekirudake", mean: "hết sức có thể" },
      { jp: "必ず", kana: "かならず", rom: "kanarazu", mean: "nhất định" },
      { jp: "絶対に", kana: "ぜったいに", rom: "zettai ni", mean: "tuyệt đối" }
    ],
    "Bài 46": [
      { jp: "届きます", kana: "とどきます", rom: "todokimasu", mean: "được giao" },
      { jp: "出ます", kana: "でます", rom: "demasu", mean: "tham gia, ra" },
      { jp: "変えます", kana: "かえます", rom: "kaemasu", mean: "đổi" },
      { jp: "間に合います", kana: "まにあいます", rom: "maniaimasu", mean: "kịp" },
      { jp: "楽します", kana: "らくします", rom: "rakushimasu", mean: "thoải mái" },
      { jp: "ところ", kana: "ところ", rom: "tokoro", mean: "nơi, điểm" },
      { jp: "最近", kana: "さいきん", rom: "saikin", mean: "gần đây" },
      { jp: "ちょうど", kana: "ちょうど", rom: "choudo", mean: "vừa mới" },
      { jp: "たったいま", kana: "たったいま", rom: "tattaima", mean: "vừa xong" },
      { jp: "そろそろ", kana: "そろそろ", rom: "sorosoro", mean: "sắp, gần" },
      { jp: "まだまだ", kana: "まだまだ", rom: "madamada", mean: "hãy còn lâu" }
    ],
    "Bài 47": [
      { jp: "集まります", kana: "あつまります", rom: "atsumarimasu", mean: "tập hợp" },
      { jp: "別れます", kana: "わかれます", rom: "wakaremasu", mean: "chia tay" },
      { jp: "長生きします", kana: "ながいきします", rom: "nagaikishimasu", mean: "sống lâu" },
      { jp: "足します", kana: "たします", rom: "tashimasu", mean: "thêm vào" },
      { jp: "祈ります", kana: "いのります", rom: "inorimasu", mean: "cầu nguyện" },
      { jp: "お天気", kana: "おてんき", rom: "otenki", mean: "thời tiết" },
      { jp: "占い", kana: "うらない", rom: "uranai", mean: "bói toán" },
      { jp: "血液型", kana: "けつえきがた", rom: "ketsuekigata", mean: "nhóm máu" },
      { jp: "事件", kana: "じけん", rom: "jiken", mean: "sự kiện, vụ việc" },
      { jp: "番組", kana: "ばんぐみ", rom: "bangumi", mean: "chương trình (TV)" },
      { jp: "内容", kana: "ないよう", rom: "naiyou", mean: "nội dung" },
      { jp: "人気", kana: "にんき", rom: "ninki", mean: "phổ biến" }
    ],
    "Bài 48": [
      { jp: "させます", kana: "させます", rom: "sasemasu", mean: "bắt (làm gì)" },
      { jp: "通います", kana: "かよいます", rom: "kayoimasu", mean: "đi lại" },
      { jp: "届けます", kana: "とどけます", rom: "todokemasu", mean: "gửi đến" },
      { jp: "嫌がります", kana: "いやがります", rom: "iyagarimasu", mean: "không muốn" },
      { jp: "自由", kana: "じゆう", rom: "jiyuu", mean: "tự do" },
      { jp: "厳しい", kana: "きびしい", rom: "kibishii", mean: "nghiêm khắc" },
      { jp: "丁寧", kana: "ていねい", rom: "teinei", mean: "lịch sự, tỉ mỉ" },
      { jp: "正しい", kana: "ただしい", rom: "tadashii", mean: "đúng, chính xác" },
      { jp: "文法", kana: "ぶんぽう", rom: "bunpou", mean: "ngữ pháp" },
      { jp: "発音", kana: "はつおん", rom: "hatsuon", mean: "phát âm" },
      { jp: "意味", kana: "いみ", rom: "imi", mean: "ý nghĩa" },
      { jp: "翻訳", kana: "ほんやく", rom: "hon'yaku", mean: "dịch thuật" }
    ],
    "Bài 49": [
      { jp: "おっしゃいます", kana: "おっしゃいます", rom: "osshaimasu", mean: "nói (kính ngữ)" },
      { jp: "いらっしゃいます", kana: "いらっしゃいます", rom: "irasshaimasu", mean: "ở, đi, đến (kính ngữ)" },
      { jp: "召し上がります", kana: "めしあがります", rom: "meshiagarimasu", mean: "ăn, uống (kính ngữ)" },
      { jp: "ご覧になります", kana: "ごらんになります", rom: "goran ni narimasu", mean: "xem (kính ngữ)" },
      { jp: "ご存じです", kana: "ごぞんじです", rom: "gozonji desu", mean: "biết (kính ngữ)" },
      { jp: "お越しになります", kana: "おこしになります", rom: "okoshi ni narimasu", mean: "đến (kính ngữ)" },
      { jp: "お目にかかります", kana: "おめにかかります", rom: "ome ni kakarimasu", mean: "gặp (khiêm nhường)" },
      { jp: "参ります", kana: "まいります", rom: "mairimasu", mean: "đi, đến (khiêm nhường)" },
      { jp: "申します", kana: "もうします", rom: "moushimasu", mean: "nói (khiêm nhường)" },
      { jp: "おります", kana: "おります", rom: "orimasu", mean: "ở (khiêm nhường)" },
      { jp: "拝見します", kana: "はいけんします", rom: "haikenshi masu", mean: "xem (khiêm nhường)" },
      { jp: "存じています", kana: "ぞんじています", rom: "zonjiteimasu", mean: "biết (khiêm nhường)" }
    ],
    "Bài 50": [
      { jp: "参ります", kana: "まいります", rom: "mairimasu", mean: "đi (khiêm nhường)" },
      { jp: "申します", kana: "もうします", rom: "moushimasu", mean: "nói (khiêm nhường)" },
      { jp: "いたします", kana: "いたします", rom: "itashimasu", mean: "làm (khiêm nhường)" },
      { jp: "拝見します", kana: "はいけんします", rom: "haikenshimasu", mean: "xem (khiêm nhường)" },
      { jp: "ご案内します", kana: "ごあんないします", rom: "goannai shimasu", mean: "hướng dẫn (khiêm nhường)" },
      { jp: "ご説明します", kana: "ごせつめいします", rom: "gosetsumei shimasu", mean: "giải thích (khiêm nhường)" },
      { jp: "お迎えに上がります", kana: "おむかえにあがります", rom: "omukae ni agarimasu", mean: "đi đón (khiêm nhường)" },
      { jp: "お持ちします", kana: "おもちします", rom: "omochi shimasu", mean: "mang (khiêm nhường)" },
      { jp: "お伝えします", kana: "おつたえします", rom: "otsutae shimasu", mean: "nhắn lại (khiêm nhường)" },
      { jp: "ただいま", kana: "ただいま", rom: "tadaima", mean: "bây giờ, ngay bây giờ" },
      { jp: "少々", kana: "しょうしょう", rom: "shoushou", mean: "một chút" },
      { jp: "お手数ですが", kana: "おてすうですが", rom: "otesuu desu ga", mean: "xin lỗi làm phiền" }
    ]
  }
};
